# Generated by Django 3.2.3 on 2021-05-31 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Username')),
                ('name', models.CharField(max_length=40, verbose_name='Name')),
                ('sex', models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'None')], max_length=6)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('vip', models.BooleanField(verbose_name='VIP')),
            ],
        ),
    ]
