# Generated by Django 3.2.3 on 2021-06-01 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'None')], max_length=6, verbose_name='Sex'),
        ),
    ]
