# Generated by Django 3.2.3 on 2021-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.EmailField(default='Unknown', max_length=100, verbose_name='Address'),
        ),
    ]
