# Generated by Django 3.2.3 on 2021-06-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20210617_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
        migrations.AlterField(
            model_name='books',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
