# Generated by Django 3.2.3 on 2021-06-20 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0002_auto_20210608_2151'),
        ('writers', '0004_auto_20210621_0054'),
        ('books', '0007_alter_books_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.classification', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='edition',
            field=models.TextField(null=True, verbose_name='Edition'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='books',
            name='price_vip',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='VIP Price'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publish_date',
            field=models.DateField(verbose_name='Publish Date'),
        ),
        migrations.AlterField(
            model_name='books',
            name='publishers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='publishers.publishers', verbose_name='Publisher'),
        ),
        migrations.AlterField(
            model_name='books',
            name='storage',
            field=models.PositiveIntegerField(default=0, verbose_name='Storage'),
        ),
        migrations.AlterField(
            model_name='books',
            name='sub_classification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.classificationsub', verbose_name='Sub-Category'),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='books',
            name='writers',
            field=models.ManyToManyField(to='writers.Writers', verbose_name='Author/Translator'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['title'], name='books_books_title_5d5dc9_idx'),
        ),
    ]
