# Generated by Django 3.2.3 on 2021-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_auto_20210621_0056'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['publishers'], name='books_books_publish_88ce0b_idx'),
        ),
    ]
