# Generated by Django 3.2.3 on 2021-06-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_books_books_books_publish_88ce0b_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['classification'], name='books_books_classif_9fca48_idx'),
        ),
        migrations.AddIndex(
            model_name='books',
            index=models.Index(fields=['sub_classification'], name='books_books_sub_cla_5628d8_idx'),
        ),
    ]
