# Generated by Django 3.2.3 on 2021-05-31 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=40, verbose_name='Username')),
                ('email', models.EmailField(max_length=40, verbose_name='E-mail')),
                ('pwd', models.CharField(max_length=128, verbose_name='Password')),
            ],
        ),
    ]
