# Generated by Django 3.2.3 on 2021-05-30 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='Name')),
                ('sex', models.CharField(choices=[(0, 'Male'), (1, 'Female'), (2, 'None')], max_length=2)),
                ('phone', models.CharField(max_length=20, verbose_name='Phone number')),
                ('email', models.EmailField(max_length=30, verbose_name='E-mail')),
                ('pwd', models.CharField(max_length=128, verbose_name='Password')),
                ('vip', models.BooleanField(verbose_name='VIP')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100, verbose_name='Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user')),
            ],
        ),
    ]
