# Generated by Django 3.2.3 on 2021-06-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='status',
            field=models.BooleanField(default=0, verbose_name='Login status'),
        ),
    ]
