# Generated by Django 3.2.3 on 2021-06-04 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='status',
        ),
        migrations.AddField(
            model_name='user',
            name='ip',
            field=models.BooleanField(default=0, verbose_name='Login ip'),
        ),
    ]
