# Generated by Django 3.2.3 on 2021-06-16 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='author_type',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Translator')], max_length=20),
        ),
    ]
