# Generated by Django 3.2.3 on 2021-06-16 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0002_alter_writers_author_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='name',
            field=models.CharField(max_length=40, verbose_name='作者名'),
        ),
    ]
