# Generated by Django 3.2.3 on 2021-06-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writers', '0003_alter_writers_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writers',
            name='author_type',
            field=models.CharField(choices=[('1', 'Author'), ('2', 'Translator')], max_length=20, verbose_name='Author type'),
        ),
        migrations.AlterField(
            model_name='writers',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
    ]
