# Generated by Django 3.2.3 on 2021-06-08 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publishers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publishers',
            name='address',
            field=models.CharField(max_length=60, verbose_name='出版社地址'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='contacts',
            field=models.CharField(max_length=40, verbose_name='联系人'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='name',
            field=models.CharField(max_length=100, verbose_name='出版社名'),
        ),
        migrations.AlterField(
            model_name='publishers',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='出版社电话'),
        ),
    ]
