# Generated by Django 3.2.3 on 2021-06-23 08:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('books', '0011_auto_20210621_0057'),
        ('users', '0004_remove_user_username'),
        ('login', '0004_alter_user_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Price')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.books')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='Order ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('confirm', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], default='N', max_length=1, verbose_name='Confirmation')),
                ('book', models.ManyToManyField(through='orders.Details', to='books.Books', verbose_name='Books')),
                ('last_edit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='Last Edit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user', verbose_name='User')),
            ],
            options={
                'verbose_name': '订单信息',
                'verbose_name_plural': '订单信息',
            },
        ),
        migrations.AddField(
            model_name='details',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
