# Generated by Django 3.2.3 on 2021-06-23 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_user_ip'),
        ('orders', '0003_alter_orders_lastedit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='lastedit',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='login.user', verbose_name='Last Edit'),
        ),
    ]
